# Generated by Django 4.2.7 on 2023-11-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_email_set_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_set_device',
            old_name='user_name',
            new_name='device_model',
        ),
        migrations.AddField(
            model_name='email_set_device',
            name='email',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
